version: '3'

services:
    dynamodb2:
        container_name: dynamodb
        image: amazon/dynamodb-local
        ports:
            - 8000:8000
        volumes:
            - dynamodata:/home/dynamodblocal
        command: "-Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb -dbPath ."

volumes:
    dynamodata:
